# PostgreSQL Connection Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_jdbc_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Automatically run schema.sql on application startup
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true