CREATE TABLE IF NOT EXISTS customer (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        full_name VARCHAR(100) NOT NULL,
                                        email VARCHAR(150) UNIQUE NOT NULL,
                                        social_security_number VARCHAR(50) UNIQUE NOT NULL
);