spring.datasource.url=jdbc:postgresql://localhost:5432/jpa_practice_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

logging.level.root=INFO
logging.level.app.jpapracticeservice=INFO
logging.level.org.hibernate.SQL=INFO

spring.data.web.pageable.one-indexed-parameters=true
spring.data.web.pageable.max-page-size=100